[package]
name = "aqua3d"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
rand = "0.8.5"
ndarray = "0.16.0"
ndarray-stats = "0.6.0"
anyhow = "*"
itertools = "*"
ordered-float = "4.5.0"